global:
  smtp_from: {{ auth_username }}
  smtp_smarthost: {{ smtp_server }}
  smtp_auth_username: {{ auth_username }}
  smtp_auth_identity: {{ auth_username }}
  smtp_auth_password: {{ auth_password }}

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: discord_general_channel
  routes:
    # devops team
    - match_re:
        type: (instance|linux|window|aws|gcp|azure)
      receiver: devops_team_discord_channel
      continue: true
      # fallback receiver
      routes:
      - receiver: devops_team_discord_channel
        match:
          severity: critical|warning|error

      - receiver: devops_manager_email
        match:
          severity: error

    # application team
    - match_re:
        type: (application|python|go|php|nodejs)
      receiver: python_team_discord_channel
      continue: true
      # fallback receiver
      routes:
      - receiver: python_team_discord_channel
        match:
          severity: critical|warning|error

      - receiver: application_manager_email
        match:
          severity: error

receivers:
# general channel
- name: discord_general_channel
  discord_configs:
  - webhook_url: {{ general_discord_webhook_url }}

# devops team
- name: devops_team_discord_channel
  discord_configs:
  - webhook_url: {{ linux_manager_group_webhook_url }}

- name: devops_manager_email
  email_configs:
    - to: {{ admin_user_email }}
      # check global config
      # from: {{ auth_username }}
      # smarthost: {{ smtp_server }}
      # auth_username: {{ auth_username }}
      # auth_identity: {{ auth_username }}
      # auth_password: {{ auth_password }}
      headers:
          subject: 'Prometheus Mail Alerts'

# application team
- name: python_team_discord_channel
  discord_configs:
  - webhook_url: {{ python_application_manager_group_webhook_url }}

- name: application_manager_email
  email_configs:
    - to: {{ python_application_manager_user_email }}
      # check global config
      # from: {{ auth_username }}
      # smarthost: {{ smtp_server }}
      # auth_username: {{ auth_username }}
      # auth_identity: {{ auth_username }}
      # auth_password: {{ auth_password }}
      headers:
          subject: 'Prometheus Mail Alerts: Notify for Applications'
