version: '3'

networks:
  monitor-net:
    driver: bridge

volumes:
  prometheus1_data: {}
  prometheus2_data: {}
  grafana_data: {}
  minio_data: {}

services:
  prometheus1:
    image: quay.io/prometheus/prometheus:v2.45.5
    container_name: prometheus1
    volumes:
      - /srv/prometheus:/etc/prometheus
      - prometheus_main_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus1.yaml"
      - "--storage.tsdb.path=/prometheus"
      # - "--storage.tsdb.retention.time=1d"
      - "--storage.tsdb.max-block-duration=1h" # 
      - "--storage.tsdb.min-block-duration=1h"
      - "--web.enable-lifecycle"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - monitor-net
    restart: always
    labels:
      org.label-schema.group: "monitoring"
  #---
  sidecar:
    image: quay.io/thanos/thanos:v0.35.0
    container_name: thanos-sidecar-1
    volumes:
      - prometheus1_data:/prometheus
      - /srv/thanos/:/etc/thanos/
    command:
      - 'sidecar'
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://prometheus-1:9090'
      - "--grpc-address=0.0.0.0:10091"
      - "--http-address=0.0.0.0:10902"
      - "--objstore.config-file=/etc/thanos/bucket/bucket_config.yml"
    networks:
      - monitor-net
    depends_on:
      - minio
      - prometheus1
    labels:
      org.label-schema.group: "monitoring"
    restart: always
  #---
  prometheus2:
    image: quay.io/prometheus/prometheus:v2.45.5
    container_name: prometheus2
    volumes:
      - /srv/prometheus:/etc/prometheus
      - prometheus_main_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus2.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.max-block-duration=1h"
      - "--storage.tsdb.min-block-duration=1h"
      - "--web.enable-lifecycle"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - monitor-net
    restart: always
    labels:
      org.label-schema.group: "monitoring"
  #---
  alertmanager:
    container_name: alertmanager
    image: quay.io/prometheus/alertmanager:v0.27.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
    restart: always
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
  #---
  