- name: provision observer server
  hosts: observer_servers
  become: yes
  tags:
    - observer
  roles:
    - docker
    - observer

- name: provision slave servers
  hosts: slave_servers
  become: yes
  tags:
    - slave_servers
  roles:
    - target 

- name: provision mysql servers and config
  hosts: slave01
  become: yes
  tags:
    - mysql_servers
  roles:
    - mysql

- name: provision thanos stack
  hosts: thanos
  become: yes
  tags:
    - thanos_stack
  roles:
    - docker-compose