{
 "title": "DuongDX Custom Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Targets ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Targets Health",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{ job }}" }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "iRate - Application latency by seconds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "irate(app_response_latency_seconds_sum[1m]) / irate(app_response_latency_seconds_count[1m])",
     "legendFormat": "{{ app_name }}{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Rate - Application latency by seconds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(app_response_latency_seconds_sum[1m]) / rate(app_response_latency_seconds_count[1m])",
     "legendFormat": "{{app_name}}{{endpoint}}"
    }
   ]
  },
  { "title": "instances metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((mem_free + mem_cached + mem_buffered) / mem_total * 100)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Instances CPU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "avg without(instance) (100 - avg_over_time(cpu_usage_idle[1m]) - avg_over_time(cpu_usage_steal[1m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk free by percentage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "job:disk_utilities_percentage:disk_sdav1_available",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}