{
 "title": "instace dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "server", "query": { "query": "label_values(host)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(system_uptime{host=\"$server\"},instance)"
    }
   },
   { "name": "disk_device", "query": { "query": "label_values(device)" } }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=~\"$server\"} / 3600",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "instance:cpu_utilities_percentage:avg_used{host=~\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "instance:memory_utilities_percentage:avg_used{host=~\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "instance:disk_used_percentage:all_device{host=~\"$server\",device=~\"$disk_device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "instance:swap_used:percentage{host=~\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Load Avg",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_load1{host=~\"$server\"}",
     "legendFormat": "load avg"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:cpu_utilities_percentage:avg_used{host=~\"$server\"}",
     "legendFormat": "average used"
    },
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\",host=~\"$server\"}",
     "legendFormat": "user"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\",host=~\"$server\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\",host=~\"$server\"}",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "MemUsage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mem_used{host=~\"$server\"}",
     "legendFormat": "used"
    },
    {
     "expr": "mem_free{host=~\"$server\"}",
     "legendFormat": "free"
    },
    {
     "expr": "swap_used{host=~\"$server\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "mem_total{host=~\"$server\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "processes_running{host=~\"$server\"}",
     "legendFormat": "{{host}}:used"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bandwidth Sent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "instance:network_bit_sent:all_ethernet{host=~\"$server\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Bandwidth Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "instance:network_bytes_recv:all_ethernet{host=~\"$server\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Received package error  %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:network_package_receive_percentage:error{host=~\"$server\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Sent package error  %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:network_package_sent_percentage:error{host=~\"$server\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Received packages dropped %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:network_package_receive_percentage:dropped{host=~\"$server\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Sent packages dropped %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:network_package_sent_percentage:dropped{host=~\"$server\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Disk  %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:disk_used_percentage:all_device{host=~\"$server\", device=~\"$disk_device\"}",
     "legendFormat": "disk used percent"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_total{host=~\"$server\",path=\"/\",device=~\"$disk_device\"}",
     "legendFormat": "{{host}}:{{path}}:total"
    },
    {
     "expr": "disk_used{host=~\"$server\",path=\"/\",device=~\"$disk_device\"}",
     "legendFormat": "{{host}}:{{path}}:used"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "instance:diskio_read_time:all_device{host=~\"$server\",name=~\"$disk_device\"}",
     "legendFormat": "{{host}}:{{ name }}:read"
    },
    {
     "expr": "instance:diskio_write_time:all_device{host=~\"$server\",name=~\"$disk_device\"}",
     "legendFormat": "{{host}}:{{ name }}:write"
    }
   ]
  },
  {
   "title": "Disk IO Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_reads{job=\"telegraf\",host=~\"$server\",name=~\"$disk_device\"}[1m])",
     "legendFormat": "{{host}}:{{name}}:read"
    },
    {
     "expr": "rate(diskio_writes{job=\"telegraf\",host=~\"$server\",name=~\"$disk_device\"}[1m])",
     "legendFormat": "{{host}}:{{name}}:write"
    }
   ]
  },
  { "title": "Mysql", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Mysql Status",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{host=~\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql Connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 35 },
   "targets": [
    {
     "expr": "instance:mysql_global_status_connections:rate1m{host=~\"$server\"}",
     "legendFormat": "connection"
    },
    {
     "expr": "instance:mysql_connection_percentage:concurrent_connecting{host=~\"$server\"}",
     "legendFormat": "current connection"
    }
   ]
  },
  {
   "title": "Mysql Connection error",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "instance:mysql_error_connection:rate1m{host=~\"$server\", error=\"accept\"}",
     "legendFormat": "accept"
    },
    {
     "expr": "instance:mysql_error_connection:rate1m{host=~\"$server\", error=\"internal\"}",
     "legendFormat": "internal"
    },
    {
     "expr": "instance:mysql_error_connection:rate1m{host=~\"$server\", error=\"select\"}",
     "legendFormat": "select"
    },
    {
     "expr": "instance:mysql_error_connection:rate1m{host=~\"$server\", error=\"max_connections\"}",
     "legendFormat": "max_connections"
    },
    {
     "expr": "instance:mysql_error_connection:rate1m{host=~\"$server\", error=\"peer_address\"}",
     "legendFormat": "max_connections"
    },
    {
     "expr": "instance:mysql_error_connection:rate1m{host=~\"$server\", error=\"tcpwrap\"}",
     "legendFormat": "max_connections"
    }
   ]
  },
  {
   "title": "Mysql open files %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:mysql_num_open_files:used_percent{host=~\"$server\"}",
     "legendFormat": "num_open_files"
    },
    {
     "expr": "instance:mysql_innodb_num_open_files:used_percent{host=~\"$server\"}",
     "legendFormat": "innodb_num_open_files"
    }
   ]
  },
  {
   "title": "Mysql Opening tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "instance:mysql_open_table:counting{host=~\"$server\"}",
     "legendFormat": "opening tables"
    }
   ]
  },
  { "title": "Mysql performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Mysql cache hit %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "instance:mysql_table_open_cache_hits_percentage:rate1m{host=~\"$server\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Mysql Full Table Scan",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 43 },
   "targets": [
    {
     "expr": "instance:mysql_full_table_scan:rate1m{host=~\"$server\"}",
     "legendFormat": "full_table_scan"
    }
   ]
  },
  {
   "title": "Mysql Slow Query",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 14, "y": 43 },
   "targets": [
    {
     "expr": "instance:mysql_slow_query:rate1m{host=~\"$server\"}",
     "legendFormat": "slow query"
    }
   ]
  }
 ]
}