---
- name: purge docker-compose and pip package
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - docker-compose
    - python-pip

- name: install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: "{{ docker_compose_cache_valid_time }}"
  with_items:
    - apt-transport-https
    - ca-certificates

- name: install python-setuptools
  apt:
    name:
      - python3
      - python3-pip
      - python-setuptools

- name: Upgrade pip3 to the latest version
  pip:
    name: pip
    state: latest
    executable: pip3