type: S3
config:
  bucket: "bucket-name"
  endpoint: "s3://bucket-name"
  # endpoint: "bucket-name"
  region: "us-east-1"
  access_key: "AccessKey"
  secret_key: "secretkey"
  insecure: false
  signature_version2: false
  encrypt_sse: false
  put_user_metadata: {}
  http_config:
    idle_conn_timeout: 90s
    response_header_timeout: 2m
    insecure_skip_verify: false
  trace:
    enable: false
  part_size: 134217728