{
 "title": "Servers Statistics",
 "tags": [ "dev" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(host)" } },
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load avg",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load1{host=~\"$server\"}",
     "legendFormat": "load avg"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_steal{cpu=\"cpu-total\",host=~\"$server\"}",
     "legendFormat": "steal"
    },
    {
     "expr": "\r\ncpu_usage_iowait{cpu=\"cpu-total\",host=~\"$server\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\",host=~\"$server\"}",
     "legendFormat": "system"
    },
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\",host=~\"$server\"}",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "MemUsage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mem_used{host=~\"$server\"}",
     "legendFormat": "used"
    },
    {
     "expr": "mem_free{host=~\"$server\"}",
     "legendFormat": "free"
    },
    {
     "expr": "swap_used{host=~\"$server\"}",
     "legendFormat": "swap"
    },
    {
     "expr": "mem_total{host=~\"$server\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "processes_running{host=~\"$server\"}",
     "legendFormat": "{{host}}:used"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(net_bytes_sent{host=~\"$server\",interface=~'eth.*|ens.*'}[1m])*8",
     "legendFormat": "{{ interface }}:out"
    },
    {
     "expr": "rate(net_bytes_recv{host=~\"$server\",interface=~'eth.*|ens.*'}[1m])*8",
     "legendFormat": "{{ interface }}:in"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{job=\"telegraf\",path=\"/\",device=\"dm-0\"}",
     "legendFormat": "{{host}}:{{path}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "disk_total{job=\"telegraf\",host=~\"$server\",path=\"/\",device=\"dm-0\"}",
     "legendFormat": "{{host}}:{{path}}:total"
    },
    {
     "expr": "disk_used{job=\"telegraf\",host=~\"$server\",path=\"/\",device=\"dm-0\"}",
     "legendFormat": "{{host}}:{{path}}:used"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_read_time{job=\"telegraf\",host=~\"$server\",name=\"dm-0\"}[1m])",
     "legendFormat": "{{host}}:{{ name }}:read"
    },
    {
     "expr": "rate(diskio_write_time{job=\"telegraf\",host=~\"$server\",name=\"dm-0\"}[1m])",
     "legendFormat": "{{host}}:{{ name }}:write"
    }
   ]
  },
  {
   "title": "Disk IO Requests",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(diskio_reads{job=\"telegraf\",host=~\"$server\",name=\"dm-0\"}[1m])",
     "legendFormat": "{{host}}:{{name}}:read"
    },
    {
     "expr": "rate(diskio_writes{job=\"telegraf\",host=~\"$server\",name=\"dm-0\"}[1m])",
     "legendFormat": "{{host}}:{{name}}:write"
    }
   ]
  },
  {
   "title": "Healthcheck",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time (ALL)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "http_response_response_time", "legendFormat": "{{server}}:{{status_code}}" }
   ]
  },
  {
   "title": "Response Time (SELF)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_response_response_time{host=\"$server\"}",
     "legendFormat": "{{server}}:{{status_code}}"
    }
   ]
  }
 ]
}