---
- name: purge docker-compose package
  yum:
    name: docker-compose
    state: removed

- name: install prerequisite
  yum:
    name:
    - python3
    - python3-pip
    - ca-certificates
    - yum-utils
    state: latest
    update_cache: yes

- name: Upgrade pip, setuptools, and wheel
  pip:
    name:
      - pip
      - setuptools
      - wheel
    state: latest
    executable: pip3