galaxy_info:
  author: DuongDX
  description: Installs docker-compose with releases from github.com/docker/compose using pip

  license: MIT

  min_ansible_version: '2.1'

  platforms:
    - name: EL
      versions:
      - '7'
    - name: Debian
      versions:
      - wheezy
      - jessie
    - name: Fedora
      versions:
      - '20'
      - '21'
      - '22'
      - '23'
      - '24'
    - name: Ubuntu
      versions:
      - trusty
      - xenial
  galaxy_tags:
      - docker
      - system
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
