global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels: # must be configured for thanos-sidecar
    cluster: 'cluster01'
    replica: '1'

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: telegraf
    metrics_path: /metrics
    # static_configs:
    # - targets: ["192.168.56.90:9273", "192.168.56.91:9273"]
    file_sd_configs:
      - files:
        - file_sd.yml
    relabel_configs:
      - source_labels: [team]
        regex: '(.*)'
        replacement: 'organization_HaNoi_${1}'
        target_label: team
      # remove active = "false"
      - source_labels: [active]
        regex: (false|inactive|drop)
        action: drop
      # keep active = "true"
      - source_labels: [active]
        regex: (true|active|keep)
        action: keep

  - job_name: aws_ec2_instance
    metrics_path: /metrics
    ec2_sd_configs:
      - access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        regex: '(.*)'
        replacement: '${1}:9100'
        target_label: __address__

rule_files:
  #- rules/prometheus_alerts_rules.yml
  - rules/instance-rules.yml
  - rules/application-rules.yml

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'