global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: telegraf
    metrics_path: /metrics
    static_configs:
    - targets: ["192.168.56.190:9273", "192.168.56.191:9273"]
  
  - job_name: program
    metrics_path: /
    static_configs:
    - targets: ["192.168.56.190:8001", "192.168.56.191:8001"]

rule_files:
  - rules/prometheus_alerts_rules.yml
  - rules/first_rule.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093