global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: telegraf
    metrics_path: /metrics
    static_configs:
    - targets: ["192.168.56.190:9273", "192.168.56.191:9273"]
  
  - job_name: node
    metrics_path: /metrics
    static_configs:
    - targets: ["192.168.56.190:9100", "192.168.56.191:9100"]

rule_files:
  - prometheus_alerts_rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093