#######################################
# install blackbox exporter on host machine
#######################################
# https://github.com/cloudalchemy/ansible-blackbox-exporter/blob/master
---
- name: create blackbox_exporter system group
  group:
    name: blackbox-exporter
    system: true
    state: present

- name: create blackbox_exporter system user
  user:
    name: blackbox-exporter
    system: true
    shell: "/usr/sbin/nologin"
    group: blackbox-exporter
    createhome: false

- name: debug
  debug:
    msg: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ architecture }}.tar.gz"

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ architecture }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ architecture }}/blackbox_exporter"
    remote_src: yes
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: create blackbox_exporter folder
  file: 
    name: /etc/blackbox
    state: directory
    mode: 0750
    owner: blackbox-exporter
    group: blackbox-exporter

- name: passing blackbox_exporter config
  template:
    src: blackbox.j2
    dest: /etc/blackbox/blackbox.yml
    mode: 0750
    owner: blackbox-exporter
    group: blackbox-exporter

- name: propagate blackbox exporter binary
  copy:
    src: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ architecture }}/blackbox_exporter"
    dest: "/usr/local/bin/blackbox_exporter"
    mode: 0750
    owner: blackbox-exporter
    group: blackbox-exporter
    remote_src: true

- name: create blackbox service
  template: 
    src: blackbox.service.j2
    dest: /etc/systemd/system/blackbox.service
    owner: root
    group: root
    mode: 0644

- name: ALLOW blackbox PING - ICMP protocol
  shell: sudo setcap cap_net_raw+ep /usr/local/bin/blackbox_exporter
  notify: restart blackbox exporter

- name: restart blackbox exporter
  systemd:
    daemon_reload: true
    name: blackbox
    state: restarted
    enabled: yes
