---
#######################################
# install and configure firewalld 
#######################################
- include_tasks: firewalld.yml
  tags: 
    - firewalld configuration

#######################################
# install telegraf on host machine
#######################################
- include_tasks: telegraf.yml
  tags: 
    - telegraf configuration

#######################################
# install blackbox exporter on host machine
#######################################
# https://github.com/cloudalchemy/ansible-blackbox-exporter/blob/master
- include_tasks: blackbox_exporter.yml
  tags: 
    - blackbox exporter configuration

#######################################
# install prometheus push gateway on host machine
#######################################
- include_tasks: promt_pushgateway.yml
  tags: 
    - pushgateway configuration