#######################################
# install prometheus push gateway on host machine
#######################################
# https://github.com/prometheus/pushgateway/releases/download/v1.7.0/pushgateway-1.7.0.linux-amd64.tar.gz
- name: create pushgateway system group
  group:
    name: pushgateway
    system: true
    state: present

- name: create pushgateway system user
  user:
    name: pushgateway
    system: true
    shell: "/usr/sbin/nologin"
    group: pushgateway
    createhome: false

- name: debug pushgateway url
  debug:
    msg: "https://github.com/prometheus/pushgateway/releases/download/v{{ pushgateway_version }}/pushgateway-{{ pushgateway_version }}.linux-{{ architecture }}.tar.gz"

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/pushgateway/releases/download/v{{ pushgateway_version }}/pushgateway-{{ pushgateway_version }}.linux-{{ architecture }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/pushgateway-{{ pushgateway_version }}.linux-{{ architecture }}/pushgateway"
    remote_src: yes
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: propagate pushgateway binary
  copy:
    src: "/tmp/pushgateway-{{ pushgateway_version }}.linux-{{ architecture }}/pushgateway"
    dest: "/usr/local/bin/pushgateway"
    mode: 0750
    owner: pushgateway
    group: pushgateway
    remote_src: true

- name: create pushgateway service
  template: 
    src: pushgateway.service.j2
    dest: /etc/systemd/system/pushgateway.service
    owner: root
    group: root
    mode: 0644


- name: restart pushgateway
  systemd:
    daemon_reload: true
    name: pushgateway
    state: restarted
    enabled: yes

- name: passing backup_data.txt file for sampling data
  copy:
    src: backup_data.txt
    dest: /tmp/backup_data.txt
    mode: 0644
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: passing file for sampling data
  copy:
    src: pushgateway_metric.sh
    dest: /tmp/pushgateway_metric.sh
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

# check /var/spool/cron/pushgateway
- name: Run CRON job to push data to PUTGATEWAY at every 1 minute of every hour.
  cron:
    cron_file: "{{ ansible_user }}"
    name: "push_data_to_push_gateway"
    user: "{{ ansible_user }}"
    minute: "*"
    hour: "*"
    job: "/tmp/pushgateway_metric.sh >> /tmp/pushgateway_cron.log 2>&1"
    state: present
